version: '3.8'

services:
  api:
    build: .
    container_name: accounting-api-prod
    restart: always
    volumes:
      - uploaded_files:/app/uploads
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - accounting-network
    # Production command without reload
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4

  db:
    image: postgres:14-alpine
    container_name: accounting-db-prod
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"  # Only expose to internal network
    networks:
      - accounting-network

networks:
  accounting-network:
    driver: bridge

volumes:
  postgres_data:
  uploaded_files: