version: '3.8'

services:
  api:
    build: .
    container_name: accounting-api
    volumes:
      - ./:/app
      - uploaded_files:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-accounting}
    depends_on:
      - db
    networks:
      - accounting-network
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14-alpine
    container_name: accounting-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-accounting}
    ports:
      - "5432:5432"
    networks:
      - accounting-network
    restart: always

networks:
  accounting-network:
    driver: bridge

volumes:
  postgres_data:
  uploaded_files: